<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>conf</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~N</string>
	<key>name</key>
	<string>nginx</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\#.*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[0-9].*</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>constant.character.brace</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\n</string>
			<key>name</key>
			<string>constant.character.end</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>constant.character.paren</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\"</string>
			<key>name</key>
			<string>constant.character.quote</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\.*\ |\~|\~\*|\!\~|\!\~\*</string>
			<key>name</key>
			<string>string.regexp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\"(.*)\"</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\'(.*)\'</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bind|browse|expvar|ext|import|header|root|gzip|index|internal|mime|on|rewrite|timeouts|templates|pprof|websocket|tls|status|redir|request_id)\b</string>
			<key>name</key>
			<string>constant.language.directive.module.main</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(basicauth)\b</string>
			<key>name</key>
			<string>constant.language.module.basicauth</string>
		</dict>
		
		<dict>
			<key>match</key>
			<string>\b(realm|resources)\b</string>
			<key>name</key>
			<string>constant.language.module.basicauth</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(errors)\b</string>
			<key>name</key>
			<string>constant.language.module.errors</string>
		</dict>
		
		<dict>
			<key>match</key>
			<string>\b(code|rotate_size|rotate_age|rotate_keep|rotate_compress)\b</string>
			<key>name</key>
			<string>constant.language.module.errors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(log)\b</string>
			<key>name</key>
			<string>constant.language.module.log</string>
		</dict>
		
		<dict>
			<key>match</key>
			<string>\b(code|rotate_size|rotate_age|rotate_keep|rotate_compress)\b</string>
			<key>name</key>
			<string>constant.language.module.log</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(fastcgi)\b</string>
			<key>name</key>
			<string>constant.language.module.fastcgi</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(root|ext|split|index|env|except|upstream|connect_timeout|read_timeout|send_timeout)\b</string>
			<key>name</key>
			<string>constant.language.module.fastcgi</string>
		</dict>
		
		<dict>
			<key>match</key>
			<string>\b(gzip)\b</string>
			<key>name</key>
			<string>constant.language.module.gzip</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ext|not|level|min_length)\b</string>
			<key>name</key>
			<string>constant.language.module.gzip</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(header)\b</string>
			<key>name</key>
			<string>constant.language.module.header</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(limit)\b</string>
			<key>name</key>
			<string>constant.language.module.limit</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(body|header)\b</string>
			<key>name</key>
			<string>constant.language.module.limit</string>
		</dict>


		<dict>
			<key>match</key>
			<string>\b(markdown)\b</string>
			<key>name</key>
			<string>constant.language.module.markdown</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ext|css|js|template|templatedir)\b</string>
			<key>name</key>
			<string>constant.language.module.markdown</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(mime)\b</string>
			<key>name</key>
			<string>constant.language.module.mime</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ext)\b</string>
			<key>name</key>
			<string>constant.language.module.mime</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(status)\b</string>
			<key>name</key>
			<string>constant.language.module.status</string>
		</dict>


		<dict>
			<key>match</key>
			<string>\b(proxy)\b</string>
			<key>name</key>
			<string>constant.language.module.proxy</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(policy|fail_timeout|max_fails|max_conns|try_duration|try_interval|health_check|health_check_port|health_check_interval|health_check_timeout|header_downstream|header_upstream|keepalive|without|except|preset|upstream|insecure_skip_verify)\b</string>
			<key>name</key>
			<string>constant.language.module.proxy</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(push)\b</string>
			<key>name</key>
			<string>constant.language.module.push</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(method|header|resources)\b</string>
			<key>name</key>
			<string>constant.language.module.push</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(redir)\b</string>
			<key>name</key>
			<string>constant.language.module.redir</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(from)\b</string>
			<key>name</key>
			<string>constant.language.module.redir</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(rewrite)\b</string>
			<key>name</key>
			<string>constant.language.module.rewrite</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(regexp|ext|if|if_op|to)\b</string>
			<key>name</key>
			<string>constant.language.module.rewrite</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(timeouts)\b</string>
			<key>name</key>
			<string>constant.language.module.timeouts</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(read|header|write|idle)\b</string>
			<key>name</key>
			<string>constant.language.module.timeouts</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(tls)\b</string>
			<key>name</key>
			<string>constant.language.module.tls</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ca|protocols|ciphers|curves|clients|load|max_certs|key_type|dns|alpn|must_staple)\b</string>
			<key>name</key>
			<string>constant.language.module.tls</string>
		</dict>

	</array>
	<key>scopeName</key>
	<string>source.caddyfile</string>
	<key>uuid</key>
	<string>0C04066A-12D2-43CA-8238-00A12CE4C14D</string>
</dict>
</plist>